apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.5.0
  name: kube-state-metrics
  namespace: monitoring
spec:
  ports:
  - name: http-metrics
    protocol: TCP
    port: 8080
  selector:
    app: kube-state-metrics
